### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by nitely** [nitely/nim-hyperx#1]
- [x] FLOW CONTROL https://httpwg.org/specs/rfc9113.html#n-the-flow-control-window
- [x] A server that is attempting to gracefully shut down a connection SHOULD send an initial GOAWAY frame with the last stream identifier set to 231-1 and a [NO_ERROR](https://httpwg.org/specs/rfc9113.html#NO_ERROR) code. This signals to the client that a shutdown is imminent and that initiating further requests is prohibited. After allowing time for any in-flight stream creation (at least one round-trip time), the server MAY send another GOAWAY frame with an updated last stream identifier. This ensures that a connection can be cleanly shut down without losing requests. https://httpwg.org/specs/rfc9113.html#GOAWAY
- [x] a server MAY request that the client abort transmission of a request without error by sending a [RST_STREAM](https://httpwg.org/specs/rfc9113.html#RST_STREAM) with an error code of [NO_ERROR](https://httpwg.org/specs/rfc9113.html#NO_ERROR) after sending a complete response (i.e., a frame with the END_STREAM flag set).
- [ ] A server SHOULD treat a request as malformed if it contains a Host header field that identifies an entity that differs from the entity in the ":authority" pseudo-header field. The values of fields need to be normalized to compare them (see [Section 6.2](https://www.rfc-editor.org/rfc/rfc3986.html#section-6.2) of [[RFC3986]](https://httpwg.org/specs/rfc9113.html#RFC3986)). An origin server can apply any normalization method, whereas other servers MUST perform scheme-based normalization (see [Section 6.2.3](https://www.rfc-editor.org/rfc/rfc3986.html#section-6.2.3) of [[RFC3986]](https://httpwg.org/specs/rfc9113.html#RFC3986)) of the two fields.
- [x] A server MUST NOT indicate that a stream has not been processed unless it can guarantee that fact. If frames that are on a stream are passed to the application layer for any stream, then [REFUSED_STREAM](https://httpwg.org/specs/rfc9113.html#REFUSED_STREAM) MUST NOT be used for that stream, and a [GOAWAY](https://httpwg.org/specs/rfc9113.html#GOAWAY) frame MUST include a stream identifier that is greater than or equal to the given stream identifier.

**Comment by nitely** [comment]
~Remove dispatcher-stream queue~

~It leads to [code like this](https://github.com/nitely/nim-hyperx/blob/aee329b842caddba118bb248df40257ca84ae90c/src/hyperx/clientserver.nim#L902-L903). It's limited to 1 single element anyway. Increasing the limit has never show any improvement.~

~It should be replaced by something like [ValueAsync](https://gist.github.com/nitely/f2c76b4eda3cc83f7f34b197a8a4e70b) (but using just 2 future vars). But the value needs to be consumed before resuming. So if closed, the dispatcher can deal with the close error while waiting for the value to be consumed.~

Done

**Comment by nitely** [comment]
fix: flow-control must take into account data frame padding.
